### ISSUE TITLE
Option to have the new tab in the style of a watermark

### ISSUE THREAD

**Issue by ryanmcnz** [fluuuid/codedoodl.es#15]
Some of the demos can be quite striking on the eyes when the previous tab being viewed is something like a page of text on a white bg.

Perhaps add an option to the extension that makes the canvas have an opacity value such as 0.2, so that it is more like a subtle animation / watermark against the background of the new tab :)

**Comment by neilcarpenter** [comment]
Moved to correct repository now: https://github.com/fluuuid/codedoodl.es-chrome-extension/issues/3
