### ISSUE TITLE
"Show Apps" button for the chrome extention

### ISSUE THREAD

**Issue by zya** [fluuuid/codedoodl.es#16]
A button that links to `chrome://apps/` 
[Earth View](https://chrome.google.com/webstore/detail/earth-view-from-google-ea/bhloflhklmhfpedakmangadcdofhnnoh?hl=en) does a similar thing which is pretty handy.

**Comment by neilcarpenter** [comment]
Have moved this to correct repository :)

https://github.com/fluuuid/codedoodl.es-chrome-extension/issues/2
