### ISSUE TITLE
No doodles show up

### ISSUE THREAD

**Issue by BadDataBadData** [fluuuid/codedoodl.es#40]
Hey, for the past few weeks, no doodles have been showing up. I took this screenshot of the chrome console, hopefully that is helpful:

![image](https://user-images.githubusercontent.com/6539710/56392496-67998f00-61e6-11e9-8cd9-1d09ff035d38.png)

I'm on Windows 10, 64 bit latest Chrome. I'm on an office network that has tight security, so maybe there's something there? But code doodles worked for me here for years... Any help greatly appreciated, love this plugin.

**Comment by neilcarpenter** [comment]
Sorry have been neglecting this project, should be back up now.

**Comment by BadDataBadData** [comment]
Thank you so much! Code doodles is amazing <3
