### ISSUE TITLE
Unminfied code

### ISSUE THREAD

**Issue by devm33** [fluuuid/codedoodl.es#8]
Why isn't the unminified code left in the repo?

It'd be nice to have access to it as a learning resource.

Thanks!

**Comment by dmnsgn** [comment]
As it is 100% community-sourced, I guess it is up to the contributors to decide if they want their code to be published.

**Comment by silviopaganini** [comment]
We had that discussion yesterday, and yeah, it's up to the contributors to put the link back to github or leave the JS unminified, we could potentially just add another field on the manifest with the source code location / gh page

**Comment by neilcarpenter** [comment]
Yeah generally just recommending doodle authors add a link back in the doodle description, for example [http://codedoodl.es/_/dmmn/substrate/](http://codedoodl.es/_/dmmn/substrate/). We can't accommodate all of the doodle code in the site repo as we would soon run out of filespace...

**Comment by devm33** [comment]
Ah ok, I didn't realize there was a space constraint.

Thanks for pointing out some of them have links to source!
